#!/usr/bin/env bash
# Open a PR against openxlings/xim-pkgindex that bumps <project> to <version>.
#
# The actual lua edit is delegated to the index repo's OWN
# `.github/scripts/version-check.py --apply --only <project>`, so this script
# stays agnostic to each package's contract:
#   - res_versioned packages (e.g. xlings): appends `["<ver>"] = "XLINGS_RES"`.
#   - url_template packages (e.g. mcpp):    downloads the artifact, computes
#     sha256, appends `["<ver>"] = { url, sha256 }`.
# and always bumps `["latest"].ref`. Existing version entries are untouched.
#
# This opens a PR only — a maintainer reviews and merges it (index git source
# is intentionally NOT on the release critical path; availability is already
# guaranteed by the xlings-res binary mirror + index artifact). On merge, the
# index repo republishes its artifact + gitee-sync picks it up.
#
# Usage: tools/bump_index.sh <project> <version>       # e.g. mcpp 0.0.82
# Auth:
#   PKGINDEX_TOKEN  (required) — write to openxlings/xim-pkgindex (clone/push/PR)
#   GITHUB_TOKEN    (optional) — GitHub API rate headroom + artifact download
#                                for url_template packages (version-check.py)
set -euo pipefail

PROJ="${1:?usage: bump_index.sh <project> <version>}"
VER="${2:?usage: bump_index.sh <project> <version>}"
INDEX_REPO="${INDEX_REPO:-openxlings/xim-pkgindex}"
BRANCH="bump/${PROJ}-${VER}"
TOKEN="${PKGINDEX_TOKEN:?PKGINDEX_TOKEN required (write to $INDEX_REPO)}"

info() { echo "[bump] $*"; }
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT

info "cloning $INDEX_REPO"
git clone -q --depth 20 "https://x-access-token:${TOKEN}@github.com/${INDEX_REPO}.git" "$WORK/idx"
cd "$WORK/idx"
git config user.email "ci@xlings.dev"
git config user.name  "xlings-ci"
git checkout -q -B "$BRANCH"

info "version-check.py --apply --only $PROJ"
# --workspace: version-check.py defaults its repo root to GITHUB_WORKSPACE,
# which inside the RELEASE repo's runner is the release repo — not this
# freshly-cloned index. Point it at the clone explicitly ("error: …/pkgs not
# found" was this default kicking in; observed on the 0.0.83 release).
python3 .github/scripts/version-check.py --workspace . --apply --only "$PROJ" > "$WORK/report.json" || {
  echo "[bump] version-check failed:" >&2; cat "$WORK/report.json" >&2 2>/dev/null || true; exit 1;
}

if git diff --quiet; then
  info "no change — index already tracks the latest $PROJ; nothing to PR"
  exit 0
fi

# Sanity: the resulting latest.ref should equal the released version. A
# mismatch usually means GitHub's releases/latest hasn't caught up yet (API
# lag) or a newer release exists — warn but still open the PR.
GOT="$(grep -oE 'ref = "[^"]+"' pkgs/*/"${PROJ}".lua 2>/dev/null | head -1 | sed -E 's/.*"([^"]+)".*/\1/' || true)"
if [[ -n "$GOT" && "$GOT" != "$VER" ]]; then
  echo "[bump] WARN: bumped latest.ref to '$GOT' but release version is '$VER' (upstream 'latest' differs?)"
fi

git add -A
git commit -qm "bump(${PROJ}): track ${VER} as latest

Auto-generated by the ${PROJ} release pipeline (bump_index.sh).
Applied via version-check.py --apply --only ${PROJ}."

info "pushing $BRANCH (force — bot branch)"
git push -q -f "https://x-access-token:${TOKEN}@github.com/${INDEX_REPO}.git" "$BRANCH"

# Open PR — idempotent: a force-push updates an already-open PR in place.
export GH_TOKEN="$TOKEN"
if gh pr view "$BRANCH" -R "$INDEX_REPO" >/dev/null 2>&1; then
  info "PR already open for $BRANCH (updated by force-push)"
else
  gh pr create -R "$INDEX_REPO" --base main --head "$BRANCH" \
    --title "bump(${PROJ}): track ${VER} as latest" \
    --body "Automated by the ${PROJ} release pipeline. Bumps \`pkgs/*/${PROJ}.lua\` \`latest.ref\` to \`${VER}\` and appends the new version entry (via \`version-check.py --apply --only ${PROJ}\`).

Merge to publish into the official index — the index repo then republishes its artifact and gitee-sync mirrors the change. Binaries are already live on \`xlings-res/${PROJ}\` (GitHub + GitCode)."
  info "PR opened"
fi
